### ISSUE TITLE
RenderPassLoadOpTests.ColorClearThenLoadAndDraw/OpenGL fails

### ISSUE THREAD

**Issue by kainino0x** [google/nxt-standalone#108]
RenderPassLoadOpTests.ColorClearThenLoadAndDraw/OpenGL (to be introduced in #107) currently fails on the OpenGL backend. Need to investigate.

**Comment by Kangz** [comment]
If it fails consistently, can you add a suppression for it?

**Comment by Kangz** [comment]
This disappeared with the change from RenderPass to RenderPassDescriptor. Closing.
