### ISSUE TITLE
Shader Model less than 5.1 causes trouble with D3DCompile

### ISSUE THREAD

**Issue by amerkoleci** [google/nxt-standalone#126]
Hi,
I saw you remap the descriptor set when compiling Vulkan GLSL to 16 * binding location, this works well for hlsl shader model 5.1 but causes trouble less than 5.1, maybe the GLSL rename scheme would be better applied also.

**Comment by Kangz** [comment]
Thanks for the info, we didn't know about that SM < 5.1 constraint. Luckily D3D12 requires SM 5.1 see the [tl;dr for the 2017-09-06 GPUWeb meeting](https://lists.w3.org/Archives/Public/public-gpu/2017Sep/0000.html). Actually it makes sense as D3D12 requires a root signature so the register number are purely to bind a name in the shader to a slot in the root signature. What has restriction from the hardware is the root signature, not the registers number themselves.

Closing, but feel free to re-open if I missed something.
