### ISSUE TITLE
Investigate building on Windows with Visual Studio 2015 Update 2

### ISSUE THREAD

**Issue by austinEng** [google/nxt-standalone#33]
The standard `Visual Studio 2015` image breaks the Windows build on AppVeyor because somewhere in the Windows SDK `AgileRef` is not being properly declared. It should be defined in `<wrl\client.h>` The issue is similar to an old Chromium issue [here](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/Iflk0jkSYeQ).

AppVeyor saw other compiler errors due to updates to the `Visual Studio 2015` image and began enabling the older `Visual Studio 2015 Update 2` image for specific accounts that requested it in this Github [issue](https://github.com/appveyor/ci/issues/891).

We may want to do the same since Chromium uses `Visual Studio 2015 Update 2` so NXT should build with the same version.

**Comment by Kangz** [comment]
Chromium doesn't use MSVC anymore, so the limit is now whatever AppVeyor supports, which compiles already.
